web+多线程/Falsk/App/models.py
#数据库调用
from flask_sqlalchemy import SQLAlchemy

db =SQLAlchemy()
def init_db(app):
    db.init_app(app)

class Person(db.Model):  # Person 是表名

    p_id = db.Column(db.Integer,primary_key=True,autoincrement=True)
    p_name =  db.Column(db.String(16))

web+多线程/Falsk/App/views.py
from flask import Blueprint,url_for,render_template,request,Response,redirect
blue = Blueprint('first_blue',__name__) #取名称

@blue.route('/1')
def hello_world():
    return "Hello World,我是蓝图，可拆分多个"

@blue.route('/urlfor/')
def urlfor():  #反向解析
    result = url_for('first_blue.hello_world') #要以蓝图名字调用
    return result

@blue.route('/APP_test/home/')
def home():
    cookies = request.cookies.get('cookie') #获取cookie 并发出去
    return render_template('/APP_test/home.html',cookies = cookies)

@blue.route('/APP_test/login/',methods =['GET','POST'])
def login():
    if request.method =="GET":
        return render_template('/APP_test/login.html')
    elif request.method == "POST":
        user =request.form.get('user')
        print(user)
        resp = Response(response="%s，登陆成功！"%user)
        resp.set_cookie('cookie',user +'！ 可查看我的cookies') #设置cookie
        return resp
@blue.route('/logout/')
def logout():
    resp = redirect(url_for('first_blue.home'))
    resp.delete_cookie('cookie')
    return resp


#魔法语法 结构标签
@blue.route('/结构标签1/')
def base1():
    return render_template('/APP_test/继承结构标签1.html')

@blue.route('/结构标签2/')
def base2():
    return render_template('/APP_test/继承结构标签2.html')

web+多线程/Falsk/app.py
from flask import Flask,render_template,request
import datetime,uuid
app = Flask(__name__)

@app.route('/user/<name>/')#默认为str <name>= 传入的变量 <int:id>整数  folat 浮点   path 能将/认为字符 不转化
def welcome(name='gfgf' ,ooo = 'girl'): #参数允许有默认值ooo =girl
    print(name,ooo)
    return 'Hello World,%s,%s'%(name,ooo)

@app.route('/')  #访问路径
def hello_world2():   #网页传入变量
    time = datetime.date.today()
    name = ["小王","小明","小红","小亮"] #列表类型
    task = {"任务":"打扫卫生","时间":"3个小时"} #字典类型
    return render_template('index.html',var =time ,list = name, dict =task)
@app.route('/getuuid/')
def get_uuid():
    print(uuid.uuid4())
    return str(uuid.uuid4())

@app.route('/test/register')  #表单提交
def register():
    return render_template("test/register.html")
@app.route('/test/result',methods =["POST","GET"]) #接收表单需要指定methods类型
def result():
    if request.method == "POST":
        result = request.form
        print(result)
        print(request.form.get('Name'))
        print (request.remote_addr) #IP获取
        return render_template("test/result.html",result=result)

#注册蓝图 结构拆分
from App.views import blue
from App.views1 import blue as blue1
app.register_blueprint(blueprint=blue)
app.register_blueprint(blueprint=blue1)
#创建数据库sqlite 数据库调用
from App.models import init_db
# app.config['SQLALCHEMY_DATABASE_URI'] ='sqlite:///sqlite3.db'
app.config['SQLALCHEMY_DATABASE_URI'] ='mysql+pymysql://root:4786874@localhost:3306/jianshu1'

app.config['SQLALCHEMY_TRACK_MODIFCATIONS'] =False
init_db(app)
if __name__ == '__main__':
    app.run(debug=True,port=8080,host='127.0.0.1')

#前端模板 https://bootstrapmade.com          https://v3.bootcss.com/
# https://colorlib.com/wp/templates/
#https://colorlib.com/wp     https://colorlib.com/wp/
#https://startbootstrap.com/themes/sb-admin-2/

web+多线程/Falsk/templates/APP_test/content.html
<div>
    <link rel="stylesheet" href="{{url_for('static',filename = 'css/content.css')}}">

    <ol>
        <li>1</li>
        <li>2</li>
        <li>3</li>
        <li>4</li>

    </ol>


    {% macro hello(name) %}
    <h4> 这是一个流水线:{{name}}</h4>
    {% endmacro %}
    {{ hello('工人')}} <!--  函数调用-->
    {{ hello()}} <!--  函数调用-->

</div>

web+多线程/Falsk/templates/APP_test/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h2>欢迎回来：{{cookies}}</h2>
<a href="{{url_for('first_blue.login')}}">登录</a>
<a href="{{url_for('first_blue.logout')}}">退出</a>


</body>
</html>

web+多线程/Falsk/templates/APP_test/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{{url_for('first_blue.login')}}" method="post">
    <table>用户名：</table><input type="text" name="user" placeholder="请输入用户名">
    <input type="submit">

</form>
</body>
</html>

web+多线程/Falsk/templates/APP_test/结构标签.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
    {% block extCSS %}
    {% endblock %}
</head>
<body>
{% block header %}
{% endblock %}

{% block content %}
{% endblock %}

{% block footer %}
{% endblock %}


{% block extJS %}
{% endblock %}


</body>
</html>

web+多线程/Falsk/templates/APP_test/继承结构标签1.html
{% extends 'APP_test/结构标签.html' %}

{% block header %}
<h2>我继承了结构标签header</h2>

{% endblock %}

web+多线程/Falsk/templates/APP_test/继承结构标签2.html
{% extends 'APP_test/继承结构标签1.html' %}

{% block header %}
{{super()}} # 如果不加super就会覆盖前面header内容
 <link rel="stylesheet" href="{{url_for('static',filename = 'css/content.css')}}">
 <h2>我再次继承了结构标签header</h2>

{% endblock %}


{% block content %}
<h2>我继承了结构标签1content</h2>
 {% include 'APP_test/content.html'  %}
{% endblock %}

web+多线程/Falsk/templates/hao321.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style type="text/css">
        /*--热门推荐--*/

#section-hot .section-hot-left{
    flex: 2;
     border: 0.1rem solid #ff9f42;
    margin-right: 1.5rem;

}
#section-hot .section-hot-left .section-hot-left_nav{
    height: 2.5rem;
    background: #ff9f42;

}
#section-hot .section-hot-left .section-hot-left_content{
display: flex;

 justify-content:center;
    align-items: center;


}

#section-hot .section-hot-left .section-hot-left_content ul li{
    flex: 1;
     /*background: #ff4040;*/
    display: inline-block;
    margin: 0 1rem;
    text-align: center;
    font-size: 1.5rem;
    line-height: 3rem;

}
#section-hot .section-hot-left .section-hot-left_content ul li:hover a{
    text-decoration: underline;
    color: red;
}

#section-hot .section-hot-right{
    flex: 7;
    /*background: gold;*/
     border: 0.1rem solid #ff9f42;
}
#section-hot .section-hot-right .section-hot-right_nav{
    height: 2.5rem;
    background: #ff9f42;
}
#section-hot .section-hot-right .section-hot-right_content{


}
.section-hot-right_content ul{
    display: inline-block; list-style:none;
}
.section-hot-right_content ul li{
    width: 9rem;
   margin: 0 auto;
    float: left;
    line-height: 2.2rem;
    font-size: 1.5rem;
    text-align: left;
    margin-left: 1.5rem;
}
.section-hot-right_content ul li:first-child{
    color: #3fff5e;;
}
.section-hot-right_content ul li:hover a{
    text-decoration: underline;
    color: red;}


    </style>
</head>
<body>
<div  class="section-hot-right_content">
     <ul>
         <li class="site-item first"><p>备注网子</p></li>
          <li><a href="http://www.hao321.co/" target="_blank">hao321主</a></li>
        <li><a href="http://www.hao321.co:88/" target="_blank">武汉房源</a></li>
          <li><a href="http://www.hao321.co/index.py" target="_blank">指数基金</a></li>
        <li><a href="http://www.hao321.co/meituan.py" target="_blank">美团商家</a></li>
          <li><a href="http://www.hao321.co/fill.html" target="_blank">小区登记</a></li>
        <li><a href="http://www.hao321.co/jl.html" target="_blank">商品套餐</a></li>
          <li><a href="https://www.pszxw.net/" target="_blank">PS自学网</a></li>
          <li><a href="http://www.51edu.com" target="_blank">精品学习网</a></li>
        <li><a href="http://zhongkao.eol.cn/" target="_blank">中国教育网</a></li>
          <li><a href="" target="_blank"></a></li>
    </ul>

    <ul>
         <li class="site-item first"><p>其他</p></li>
          <li><a href="http://www.hao321.co/xqsj.py" target="_blank">小区数据</a></li>
        <li><a href="http://www.hao321.co/jlsj.py" target="_blank">商品数据</a></li>
          <li><a href="https://open.163.com/" target="_blank">网易公开课</a></li>
        <li><a href="https://ke.qq.com/" target="_blank">腾讯课堂</a></li>
          <li><a href="https://uiiiuiii.com/" target="_blank">优优教程网</a></li>
        <li><a href="https://www.bangongziyuan.com/" target="_blank">办公资源网</a></li>
          <li><a href="https://www.pszxw.net/" target="_blank">PS自学网</a></li>
          <li><a href="http://www.51edu.com" target="_blank">精品学习网</a></li>
        <li><a href="http://zhongkao.eol.cn/" target="_blank">中国教育网</a></li>
          <li><a href="" target="_blank"></a></li>
    </ul>

</div>
</body>
</html>

web+多线程/Falsk/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
现在时间是{{var}}<br>

值班人员有：<br>
{% for data in list %}<!--大括号和百分号起控制结构，还有if-->
  {% if loop.index0 ==2 %}
     <li style="color: red">{{ data }}:{{loop.index0}}</li>     <!-- loop.index0获取序号 data|tojosn 可使用tojosn转化为json格式 -->
  {% else %}
     <li style="color:green">{{ data }}:{{loop.index0}}</li>
    {% endif %}

{% endfor %}

任务：<br>
<table>
    {% for key,value in dict.items() %}

    <tr>
        <td>{{key}}:</td>
        <td>{{value}}</td>
    </tr>

     {% endfor %}
</table>



</body>
</html>

web+多线程/Falsk/templates/index1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<ul>
    {% for person in persons  %}
     <li>{{person.p_name}}</li>
    {% endfor %}

</ul>
</body>
</html>